DDCYLS-5011 - Update AMLS confirmation pages
hmrc/amls-frontend pull request #1675
Opened 2024-07-25 13:20 UTC by lewis-nicholls

… registration [renewal] & update information confirmation pages).

Updated Panels to include the AMLS reference on registration and renewal journeys. Updated some of the main body content on registration, re registration [renewal] & update information confirmation pages. Removal of continue button replaced by a 'Go to Your Registration' link on registration journey to navigate user to dashboard. Removal of continue button replaced by a 'Return to Your Registration' link on renewal journey to navigate user to dashboard. Removal of the exit survey from all AMLS Dashboards (different dashboards for each status).

[Your pull request description here]

## Related / Dependant PRs?

## How Has This Been Tested?

## Checklist

- [ ] Breaking change (fix or feature that would cause existing functionality to change).
- [ ] Build passing.
- [ ] Unit tests have full coverage.
- [ ] Unit test approach and implementation has been reviewed with QA (testers).
- [ ] Requires acceptance test run.
- [ ] Appropriate labels added.
- [ ] RELEASE NOTES ADDED.

2024-07-26 10:01 UTC, lewishay requested changes

2024-07-30 12:47 UTC, lewis-nicholls commented on app/views/confirmation/ConfirmationBacsView.scala.html
> +    <p class="govuk-body">
amended acceptance tests.

2024-07-30 12:47 UTC, lewis-nicholls commented on app/views/confirmation/ConfirmationNoFeeView.scala.html
> +    <p class="govuk-body">
amended acceptance tests.

2024-07-30 12:47 UTC, lewis-nicholls commented on app/views/confirmation/ConfirmationBacsView.scala.html
> +    HtmlFormat.fill(
new commit has been added to PR.

2024-07-30 15:34 UTC, lewishay approved these changes

2024-07-31 06:44 UTC, merged