DDCYLS-4660 - Missing fieldsets and legends (checkboxes)
hmrc/amls-frontend pull request #1691
Opened 2024-08-08 10:00 UTC by lewis-nicholls

…et tag. Updating the following pages to now include.

[Your pull request description here]

## Related / Dependant PRs?

## How Has This Been Tested?

## Checklist

- [ ] Breaking change (fix or feature that would cause existing functionality to change).
- [ ] Build passing.
- [ ] Unit tests have full coverage.
- [ ] Unit test approach and implementation has been reviewed with QA (testers).
- [ ] Requires acceptance test run.
- [ ] Appropriate labels added.
- [ ] RELEASE NOTES ADDED.

2024-08-08 14:27 UTC, VJWatson approved these changes

2024-08-09 09:48 UTC, dnyuar requested changes
One comment about the `HowCashPaymentsReceivedView`, other than that looks all good

2024-08-09 09:48 UTC, dnyuar commented on app/views/renewal/HowCashPaymentsReceivedView.scala.html
> +                        content = Text(messages("renewal.cash.payments.received.title")),
The hint text has moved to the top of the page but should be below the heading.

<img width="1792" alt="Screenshot 2024-08-09 at 10 05 48" src="https://github.com/user-attachments/assets/acbd843a-6763-4896-b357-c38e9194d69f">

<img width="1792" alt="Screenshot 2024-08-09 at 10 09 33" src="https://github.com/user-attachments/assets/84711dcc-4c09-436f-a695-d757ea914c82">

2024-08-12 11:13 UTC, lewis-nicholls commented
amendment to HowCashPaymentsReceivedView.scala.html to ensure spacing was correct. This has involved using the visually hidden class within the fieldset.

2024-08-12 13:00 UTC, dnyuar approved these changes

2024-08-12 13:02 UTC, merged